import { CHECKMATE_SCORE } from "./eval";

export const ASPIRATION_WINDOW_MIN_DEPTH = 4;
export const ASPIRATION_WINDOW_INITIAL_DELTA = 5;
export const ASPIRATION_WINDOW_DELTA_GROWTH_FACTOR = 1.34375;
export const ASPIRATION_WINDOW_MAX_DELTA = CHECKMATE_SCORE;
export const ASPIRATION_WINDOW_MATE_SCORE_THRESHOLD = CHECKMATE_SCORE - 1000;
