export const CORRECTION_HISTORY_TABLE_SIZE = 1 << 15;
export const CORRECTION_HISTORY_TABLE_MASK =
  CORRECTION_HISTORY_TABLE_SIZE - 1;
export const CORRECTION_HISTORY_COLOR_COUNT = 2;
export const CORRECTION_HISTORY_SCALE = 256;
export const CORRECTION_HISTORY_WEIGHT_SCALE = 32;
export const CORRECTION_HISTORY_MAX_UPDATE_WEIGHT = 16;
export const CORRECTION_HISTORY_MAX_CORRECTION = 1_024;
export const CORRECTION_HISTORY_MATE_SCORE_BUFFER = 1_000;
