export const LATE_MOVE_REDUCTION_MIN_DEPTH = 3;
export const LATE_MOVE_REDUCTION_MIN_MOVE_INDEX = 3;
export const LATE_MOVE_REDUCTION_BASE = 1;
export const LATE_MOVE_REDUCTION_DEPTH_DIVISOR = 6;
export const LATE_MOVE_REDUCTION_MOVE_INDEX_DIVISOR = 8;
