export const MOVE_LOOP_FUTILITY_PRUNING_MAX_DEPTH = 3;
export const MOVE_LOOP_FUTILITY_PRUNING_MIN_MOVE_INDEX = 1;
export const MOVE_LOOP_FUTILITY_MARGIN_BASE = 120;
export const MOVE_LOOP_FUTILITY_MARGIN_PER_DEPTH = 160;
export const MOVE_LOOP_FUTILITY_PRUNING_MATE_SCORE_BUFFER = 1_000;
