export const NNUE_ARCHITECTURE_NAME =
  "HalfKAv2_hm-FullThreats-L1024-L31-L32-v1";

export const NNUE_SQUARE_COUNT = 64;
export const NNUE_COLOR_COUNT = 2;
export const NNUE_PIECE_SQUARE_NONE = 0;
export const NNUE_PIECE_SQUARE_BUCKET_SIZE = 704;
export const NNUE_HALF_KA_FEATURE_DIMENSIONS = 22_528;
export const NNUE_FULL_THREATS_FEATURE_DIMENSIONS = 60_720;
export const NNUE_TRANSFORMED_FEATURE_DIMENSIONS = 1_024;
export const NNUE_TRANSFORMED_FEATURES_PER_PERSPECTIVE =
  NNUE_TRANSFORMED_FEATURE_DIMENSIONS / 2;
export const NNUE_FC_0_OUTPUTS = 31;
export const NNUE_FC_1_OUTPUTS = 32;
export const NNUE_PSQ_BUCKETS = 8;
export const NNUE_LAYER_STACKS = 8;
export const NNUE_OUTPUT_SCALE = 16;
export const NNUE_WEIGHT_SCALE_BITS = 6;
export const NNUE_FT_MAX = 255;
export const NNUE_HIDDEN_ONE = 128;
export const NNUE_HIDDEN_MAX = 127;
export const NNUE_FEATURE_TRANSFORMER_PRODUCT_SHIFT = 9;
export const NNUE_FEATURE_TRANSFORMER_PRODUCT_DENOMINATOR =
  1 << NNUE_FEATURE_TRANSFORMER_PRODUCT_SHIFT;
export const NNUE_MAX_ACTIVE_HALF_KA_FEATURES = 32;
export const NNUE_MAX_ACTIVE_FULL_THREAT_FEATURES = 128;
export const NNUE_ACCUMULATOR_STACK_CAPACITY = 256;

export const NNUE_FC_0_ACTIVATION_INPUTS = NNUE_FC_0_OUTPUTS * 2;
export const NNUE_FC_0_OUTPUTS_WITH_BUCKET = NNUE_FC_0_OUTPUTS + 1;
export const NNUE_FEATURE_VECTOR_DIMENSIONS =
  NNUE_TRANSFORMED_FEATURE_DIMENSIONS;
export const NNUE_HALF_KA_WEIGHT_COUNT =
  NNUE_HALF_KA_FEATURE_DIMENSIONS * NNUE_TRANSFORMED_FEATURE_DIMENSIONS;
export const NNUE_HALF_KA_PSQ_WEIGHT_COUNT =
  NNUE_HALF_KA_FEATURE_DIMENSIONS * NNUE_PSQ_BUCKETS;
export const NNUE_FULL_THREAT_WEIGHT_COUNT =
  NNUE_FULL_THREATS_FEATURE_DIMENSIONS * NNUE_TRANSFORMED_FEATURE_DIMENSIONS;
export const NNUE_FULL_THREAT_PSQ_WEIGHT_COUNT =
  NNUE_FULL_THREATS_FEATURE_DIMENSIONS * NNUE_PSQ_BUCKETS;
export const NNUE_FC_0_WEIGHT_COUNT =
  NNUE_FEATURE_VECTOR_DIMENSIONS * NNUE_FC_0_OUTPUTS_WITH_BUCKET;
export const NNUE_FC_1_WEIGHT_COUNT =
  NNUE_FC_0_ACTIVATION_INPUTS * NNUE_FC_1_OUTPUTS;
export const NNUE_FC_2_WEIGHT_COUNT = NNUE_FC_1_OUTPUTS;

export const NNUE_KING_BUCKETS = new Int32Array([
  28, 29, 30, 31, 31, 30, 29, 28,
  24, 25, 26, 27, 27, 26, 25, 24,
  20, 21, 22, 23, 23, 22, 21, 20,
  16, 17, 18, 19, 19, 18, 17, 16,
  12, 13, 14, 15, 15, 14, 13, 12,
  8, 9, 10, 11, 11, 10, 9, 8,
  4, 5, 6, 7, 7, 6, 5, 4,
  0, 1, 2, 3, 3, 2, 1, 0,
]);

export const NNUE_ORIENT_TABLE = new Int8Array([
  7, 7, 7, 7, 0, 0, 0, 0,
  7, 7, 7, 7, 0, 0, 0, 0,
  7, 7, 7, 7, 0, 0, 0, 0,
  7, 7, 7, 7, 0, 0, 0, 0,
  7, 7, 7, 7, 0, 0, 0, 0,
  7, 7, 7, 7, 0, 0, 0, 0,
  7, 7, 7, 7, 0, 0, 0, 0,
  7, 7, 7, 7, 0, 0, 0, 0,
]);

export const NNUE_MODEL_BINARY_MAGIC = "DCE_NNUE";
export const NNUE_MODEL_BINARY_VERSION = 2;
export const NNUE_DEFAULT_RANDOM_SEED = 0x4d595df4;
