export const REVERSE_FUTILITY_PRUNING_MAX_DEPTH = 3;
export const REVERSE_FUTILITY_MARGIN_BASE = 80;
export const REVERSE_FUTILITY_MARGIN_PER_DEPTH = 120;
export const REVERSE_FUTILITY_MATE_SCORE_BUFFER = 1_000;
