export const REVERSE_FUTILITY_PRUNING_MAX_DEPTH = 16;
export const REVERSE_FUTILITY_MARGIN_BASE = 80;
export const REVERSE_FUTILITY_MARGIN_PER_DEPTH = 80;
export const REVERSE_FUTILITY_MATE_SCORE_BUFFER = 1_000;
