export const SINGULAR_EXTENSION_MIN_DEPTH = 6;
export const SINGULAR_EXTENSION_TT_DEPTH_MARGIN = 3;
export const SINGULAR_EXTENSION_BETA_MARGIN_PER_DEPTH = 16;
export const SINGULAR_EXTENSION_SEARCH_DEPTH_DIVISOR = 2;
export const SINGULAR_EXTENSION_AMOUNT = 1;
export const SINGULAR_EXTENSION_MATE_SCORE_BUFFER = 1_000;
