import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const inputPath = resolve("build/nnue.wasm");
const outputPath = resolve("src/search/nnue/nnueWasmBinary.generated.ts");
const bytes = await readFile(inputPath);
const source = `// Generated by npm run build. Do not edit.\nexport default ${JSON.stringify(
  bytes.toString("base64"),
)};\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source);
