export const CASTLING_RIGHTS = {
  WHITE_KINGSIDE: 1 << 0, // 0001
  WHITE_QUEENSIDE: 1 << 1, // 0010
  BLACK_KINGSIDE: 1 << 2, // 0100
  BLACK_QUEENSIDE: 1 << 3, // 1000
};

// King origin squares
export const WHITE_KING_ORIGIN_SQUARE = 4; // e1
export const BLACK_KING_ORIGIN_SQUARE = 60; // e8

// Rook origin squares
export const WHITE_KINGSIDE_ROOK_ORIGIN_SQUARE = 7; // h1
export const WHITE_QUEENSIDE_ROOK_ORIGIN_SQUARE = 0; // a1
export const BLACK_KINGSIDE_ROOK_ORIGIN_SQUARE = 63; // h8
export const BLACK_QUEENSIDE_ROOK_ORIGIN_SQUARE = 56; // a8

// King destination squares
export const WHITE_KING_KINGSIDE_CASTLE_DESTINATION_SQUARE = 6; // g1
export const WHITE_KING_QUEENSIDE_CASTLE_DESTINATION_SQUARE = 2; // c1
export const BLACK_KING_KINGSIDE_CASTLE_DESTINATION_SQUARE = 62; // g8
export const BLACK_KING_QUEENSIDE_CASTLE_DESTINATION_SQUARE = 58; // c8

// Rook destination squares
export const WHITE_ROOK_KINGSIDE_CASTLE_DESTINATION_SQUARE = 5; // f1
export const WHITE_ROOK_QUEENSIDE_CASTLE_DESTINATION_SQUARE = 3; // d1;
export const BLACK_ROOK_KINGSIDE_CASTLE_DESTINATION_SQUARE = 61; // f8
export const BLACK_ROOK_QUEENSIDE_CASTLE_DESTINATION_SQUARE = 59; // d8;
