export const GAME_STATE = {
  ONGOING: 0,
  CHECKMATE: 1,
  STALEMATE: 2,
  DRAW: 3,
} as const;

export const GAME_END_STATES = [
  GAME_STATE.CHECKMATE,
  GAME_STATE.STALEMATE,
  GAME_STATE.DRAW,
];

export const GAME_END_REASON = {
  CHECKMATE: 0,
  STALEMATE: 1,
  REPETITION: 2,
  HALFMOVE_CLOCK: 3,
  INSUFFICIENT_MATERIAL: 4,
} as const;

export const REPETITION_COUNT_LEADING_TO_DRAW = 3;
export const HALFMOVE_CLOCK_COUNT_LEADING_TO_DRAW = 100;
