import { BISHOP_INDEX, KING_INDEX, KNIGHT_INDEX, PAWN_INDEX, QUEEN_INDEX, ROOK_INDEX } from "../constants/piece";

const STANDARD_NOTATION_FILE_A = 'a';
const STANDARD_NOTATION_FILE_B = 'b';
const STANDARD_NOTATION_FILE_C = 'c';
const STANDARD_NOTATION_FILE_D = 'd';
const STANDARD_NOTATION_FILE_E = 'e';
const STANDARD_NOTATION_FILE_F = 'f';
const STANDARD_NOTATION_FILE_G = 'g';
const STANDARD_NOTATION_FILE_H = 'h';

export const INTERNAL_FILE_TO_STANDARD_NOTATION_FILE: Record<number, string> = {
  0: STANDARD_NOTATION_FILE_A,
  1: STANDARD_NOTATION_FILE_B,
  2: STANDARD_NOTATION_FILE_C,
  3: STANDARD_NOTATION_FILE_D,
  4: STANDARD_NOTATION_FILE_E,
  5: STANDARD_NOTATION_FILE_F,
  6: STANDARD_NOTATION_FILE_G,
  7: STANDARD_NOTATION_FILE_H,
};

export const STANDARD_NOTATION_FILE_TO_INTERNAL_FILE: Record<string, number> = {
  [STANDARD_NOTATION_FILE_A]: 0,
  [STANDARD_NOTATION_FILE_B]: 1,
  [STANDARD_NOTATION_FILE_C]: 2,
  [STANDARD_NOTATION_FILE_D]: 3,
  [STANDARD_NOTATION_FILE_E]: 4,
  [STANDARD_NOTATION_FILE_F]: 5,
  [STANDARD_NOTATION_FILE_G]: 6,
  [STANDARD_NOTATION_FILE_H]: 7,
};

export const VALID_STANDARD_NOTATION_FILES = [STANDARD_NOTATION_FILE_A, STANDARD_NOTATION_FILE_B, STANDARD_NOTATION_FILE_C, STANDARD_NOTATION_FILE_D, STANDARD_NOTATION_FILE_E, STANDARD_NOTATION_FILE_F, STANDARD_NOTATION_FILE_G, STANDARD_NOTATION_FILE_H];

const STANDARD_NOTATION_ROOK = 'r';
const STANDARD_NOTATION_KNIGHT = 'n';
const STANDARD_NOTATION_BISHOP = 'b';
const STANDARD_NOTATION_QUEEN = 'q';
const STANDARD_NOTATION_KING = 'k';
const STANDARD_NOTATION_PAWN = 'p';

export const INTERNAL_PIECE_TO_STANDARD_NOTATION_PIECE: Record<number, string> = {
  [ROOK_INDEX]: STANDARD_NOTATION_ROOK,
  [KNIGHT_INDEX]: STANDARD_NOTATION_KNIGHT,
  [BISHOP_INDEX]: STANDARD_NOTATION_BISHOP,
  [QUEEN_INDEX]: STANDARD_NOTATION_QUEEN,
  [KING_INDEX]: STANDARD_NOTATION_KING,
  [PAWN_INDEX]: STANDARD_NOTATION_PAWN,
};

export const STANDARD_NOTATION_PIECE_TO_INTERNAL_PIECE: Record<string, number> = {
  [STANDARD_NOTATION_ROOK]: ROOK_INDEX,
  [STANDARD_NOTATION_KNIGHT]: KNIGHT_INDEX,
  [STANDARD_NOTATION_BISHOP]: BISHOP_INDEX,
  [STANDARD_NOTATION_QUEEN]: QUEEN_INDEX,
  [STANDARD_NOTATION_KING]: KING_INDEX,
  [STANDARD_NOTATION_PAWN]: PAWN_INDEX
};

export const VALID_STANDARD_NOTATION_PIECES = [STANDARD_NOTATION_ROOK, STANDARD_NOTATION_KNIGHT, STANDARD_NOTATION_BISHOP, STANDARD_NOTATION_QUEEN, STANDARD_NOTATION_KING, STANDARD_NOTATION_PAWN];

export const VALID_STANDARD_NOTATION_PROMOTION_PIECES = [STANDARD_NOTATION_ROOK, STANDARD_NOTATION_BISHOP, STANDARD_NOTATION_KNIGHT, STANDARD_NOTATION_QUEEN];